<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest.TestAdapter" Version="4.*" />
    <PackageReference Include="MSTest.TestFramework" Version="4.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FireDemo/FireDemo.csproj" />
  </ItemGroup>

</Project>
